// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL2t25Qr2ItisVx6D04Nh99SoJNXEBcIw',
    appId: '1:10158927928:web:41c8754fc8bd785cfd36cd',
    messagingSenderId: '10158927928',
    projectId: 'recover-ai-49f0d',
    authDomain: 'recover-ai-49f0d.firebaseapp.com',
    storageBucket: 'recover-ai-49f0d.firebasestorage.app',
    measurementId: 'G-2BP2NE0GYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2DAdxjzTovb3QLxzOcnv3s42C33LsQs',
    appId: '1:10158927928:android:e134efa42878069efd36cd',
    messagingSenderId: '10158927928',
    projectId: 'recover-ai-49f0d',
    storageBucket: 'recover-ai-49f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4jKixOOhR9Acq0-_lv4SHQb-FKSyVEaU',
    appId: '1:10158927928:ios:3e01d682b04b5706fd36cd',
    messagingSenderId: '10158927928',
    projectId: 'recover-ai-49f0d',
    storageBucket: 'recover-ai-49f0d.firebasestorage.app',
    iosBundleId: 'com.quantumcrafters.recoverAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4jKixOOhR9Acq0-_lv4SHQb-FKSyVEaU',
    appId: '1:10158927928:ios:3e01d682b04b5706fd36cd',
    messagingSenderId: '10158927928',
    projectId: 'recover-ai-49f0d',
    storageBucket: 'recover-ai-49f0d.firebasestorage.app',
    iosBundleId: 'com.quantumcrafters.recoverAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL2t25Qr2ItisVx6D04Nh99SoJNXEBcIw',
    appId: '1:10158927928:web:83551a18c503bd49fd36cd',
    messagingSenderId: '10158927928',
    projectId: 'recover-ai-49f0d',
    authDomain: 'recover-ai-49f0d.firebaseapp.com',
    storageBucket: 'recover-ai-49f0d.firebasestorage.app',
    measurementId: 'G-T4D38X9DW8',
  );
}
